### ISSUE TITLE
MP4 recording

### ISSUE THREAD

**Issue by gomes2191** [amikha1lov/RecApp#37]
Allow recording in mp4 format, since most social media support only that format.

**Comment by amikha1lov** [comment]
Hey.  thank you for the idea.  I will try to implement this in future releases, possibly in the next

**Comment by tim77** [comment]
MP4 added in `1.1.0` version. Flatpak update 🔜

**Comment by gomes2191** [comment]
> MP4 added in `1.1.0` version. Flatpak update soon

Has not been updated on flathub continues in version 1.0.4 version without support for mp4.

**Comment by tim77** [comment]
It's updated and published now on Flathub. Please test.

**Comment by gomes2191** [comment]
> It's updated and published now on Flathub. Please test.

Tested and approved it worked perfectly ...
