### ISSUE TITLE
Any keyboard shorcut

### ISSUE THREAD

**Issue by nazar2sfive** [amikha1lov/RecApp#40]
to start and stop recording?

**Comment by amikha1lov** [comment]
Hello.  Glad you paid attention to my application.
Ctrl + R start / stop recording
Ctrl + A sound on / off
Ctrl + h enable / disable high quality recording
Ctrl + m enable / disable mouse cursor recording
Ctrl + q quit app
what else would you like to add to the application?

**Comment by nazar2sfive** [comment]
nice. I wish there was info about it somewhere in the app where i could see this shortcut.

**Comment by amikha1lov** [comment]
will be added in future versions

**Comment by SeaDve** [comment]
Planning to add it with Gtk.ShortcutsWindow
