### ISSUE TITLE
Gif format recording

### ISSUE THREAD

**Issue by gomes2191** [amikha1lov/RecApp#62]
It would be interesting to insert the possibility of recording in gif if possible considering that sites like "Gitlab" and "Github" do not allow the upload of video, sometimes it is necessary to insert animation to report a problem and the possibility of inserting support for recording in Gif format would help a lot.
You are to be congratulated the application is very useful.

**Comment by amikha1lov** [comment]
There is no way to implement recording screencast in GIF format without using ffmpeg. But our goal is not to use ffmpeg, so it means that there won't be any GIF support in RecApp"
