### ISSUE TITLE
turkish language

### ISSUE THREAD

**Issue by usolmz** [amikha1lov/RecApp#86]
Turkish language 
https://github.com/usolmz/RecApp/tree/master/po
https://github.com/usolmz/RecApp/pull/1

**Comment by SeaDve** [comment]
Hi, thanks for the translation. Although you also have to add "tr" on the LINGUAS file

**Comment by amikha1lov** [comment]
Hi. Thank you. 

"Turkish language" is wrong name for PO file. It should be tr.po

**Comment by usolmz** [comment]
I changed the title
